### PR TITLE
Speed up related projects calculations

### PR DESCRIPTION
**Pull request by aerialist7**
The caching mechanism speeds up the related projects calculation time by 4-5 times (~22s -> ~4s)

### CODE REVIEW

**Comment by turansky** [comment]
cc @stefanthaler

**Comment by aerialist7** [comment]
@turansky, do you need something else?

**Comment by turansky** [comment]
Initial problem was introduced #17. 
And looks like small fix in `filter` will work.  

In any case solution with `static` constants as "cache" - isn't Gradle way :(

cc @stefanthaler @sgrishchenko

**Comment by aerialist7** [comment]
@turansky, no. 
The initial problem was introduced a long time ago.

During the migration to the typesafe project dependencies, we've got big speedup on dev-server restart (without fix of #17), but it was unclear what is the reason for the speedup. But after Stefan's I realized that the root-cause was in KFC, because after his fix we've got very long dev-server restart again.

Then I made a caching mechanism and checked it via `includeBuild`, so now it works very quick

**Comment by aerialist7** [comment]
> In any case solution with static constants as "cache" - isn't Gradle way :(

Okay, then please clarify what the "Gradle" way is?

**Review by turansky — CHANGES_REQUESTED** [review]
Cache invalidation missed

**Review by turansky — COMMENTED** [review]
Still missed invalidation

**Review by turansky — CHANGES_REQUESTED** [review]
Please provide Gradle Doc link, where such cache described

**Pull request closed without merging**
